version: "2"
services:
    # to run just the backend
    # docker run -v $PWD/config-rinkeby-sim:/config -v $PWD/logs:/var/log/tc/  --entrypoint tc --rm -p 8123:8123 bl4ck5un/tc-core:Debug
    tc-core:
        image: "bl4ck5un/tc-core:Debug"
        network_mode: host
        entrypoint: "tc"
        volumes:
          - ./config-rinkeby-sim:/config
          - ./logs:/var/log/tc/
    tc-relay:
        env_file:
          - .env
        depends_on:
          - tc-core
        image: "bl4ck5un/tc-relay"
        network_mode: host
        # command: "--dryrun"
        command: "--catchup"
