version: "2"
services:
    tc-core:
        image: "bl4ck5un/tc-core:Debug"
        network_mode: host
        entrypoint: "tc"
        volumes:
          - ./config-rinkeby-sim:/config
          - ./logs:/var/log/tc/
    tc-relay:
        env_file:
          - ./infura_credentials.env
        depends_on:
          - tc-core
        image: "bl4ck5un/tc-relay"
        network_mode: host
        command: "--dryrun"
